name: propert_ez
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts-Montserrat/

  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts-Montserrat/Montserrat-Light.ttf
        weight: 300
      - asset: assets/fonts-Montserrat/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts-Montserrat/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts-Montserrat/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts-Montserrat/Montserrat-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts-Montserrat/Montserrat-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts-Montserrat/Montserrat-MediumItalic.ttf
        weight: 500
        style: italic

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo2.jpeg"

flutter_native_splash:
  color: "#011019"
  image: assets/images/logo2.jpeg
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
